
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "NUMsequencia : sentido intervalossentido : '+'sentido : '-'intervalos : intervalointervalos : intervalos intervalointervalo : '[' NUM ',' NUM ']'"
    
_lr_action_items = {'+':([0,],[3,]),'-':([0,],[4,]),'$end':([1,5,6,8,12,],[0,-1,-4,-5,-6,]),'[':([2,3,4,5,6,8,12,],[7,-2,-3,7,-4,-5,-6,]),'NUM':([7,10,],[9,11,]),',':([9,],[10,]),']':([11,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sequencia':([0,],[1,]),'sentido':([0,],[2,]),'intervalos':([2,],[5,]),'intervalo':([2,5,],[6,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sequencia","S'",1,None,None,None),
  ('sequencia -> sentido intervalos','sequencia',2,'p_sequencia','intervalos_yacc.py',14),
  ('sentido -> +','sentido',1,'p_sentidoA','intervalos_yacc.py',18),
  ('sentido -> -','sentido',1,'p_sentidoD','intervalos_yacc.py',22),
  ('intervalos -> intervalo','intervalos',1,'p_intervalos_intervalo','intervalos_yacc.py',26),
  ('intervalos -> intervalos intervalo','intervalos',2,'p_intervalos_intervalos','intervalos_yacc.py',30),
  ('intervalo -> [ NUM , NUM ]','intervalo',5,'p_intervalo','intervalos_yacc.py',35),
]
